### ISSUE TITLE
Mijn Account -> Email 

### ISSUE THREAD

**Issue by DamianPuzik** [SteRompen/webapp-b2c6#15]
Wanneer je in ''account'' zit en op email klikt krijg je de volgende error: 

Error.
An error occurred while processing your request.
Request ID: 00-65c2c257dc20a40fae25800ed60e0016-232ec83adc7a4a63-00

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by SteRompen** [comment]
Ook bij dit issue zat het probleem in het veranderen van de klasse IdentityUser naar onze custom AppUser. Dit is hier ook aangepast en werkt naar behoren.
