### ISSUE TITLE
Mijn Account -> Two-factor authentication

### ISSUE THREAD

**Issue by DamianPuzik** [SteRompen/webapp-b2c6#16]
Wanneer je in ''account'' zit en op ''Two-factor authentication'' klikt krijg je de volgende error:

Error.
An error occurred while processing your request.
Request ID: 00-f39e788fdfca5b135ca2ad3b6522dda6-f3042c27bfce7726-00

Development Mode
Swapping to Development environment will display more detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by SteRompen** [comment]
functionaliteit voor ons niet relevant en daarmee eruit gehaald.
